services:
  arbitration_graphs_pybind_devel:
    build:
      context: .
      target: devel
    image: arbitration_graphs_pybind_devel
    env_file: .env
    volumes:
      - ..:/home/blinky/arbitration_graphs

  wheel_builder:
    build:
      context: ..
      dockerfile: python_bindings/Dockerfile
      target: wheel_builder
    image: arbitration_graphs_wheel_builder

