services:
  arbitration_graphs_pacman_demo:
    extends:
      file: ../docker-compose.yaml
      service: arbitration_graphs
    image: arbitration_graphs_pacman_demo
    volumes:
      - .:/home/blinky/demo