services:
  tutorial:
    image: ghcr.io/kit-mrt/arbitration_graphs_pacman_tutorial:$VERSION
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/home/blinky/demo
      - $HOME/.Xauthority:/home/blinky/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    #
    # This makes sure `docker compose up` only runs the demo service
    # Use `docker compose run --rm --service-ports tutorial` to run the tutorial
    profiles: ["tutorial"]

  demo:
    image: ghcr.io/kit-mrt/arbitration_graphs_pacman_demo:$VERSION
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - $HOME/.Xauthority:/home/blinky/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY

