name: Bump version, create and test release, and push Docker images
on:
  pull_request:
    types:
      - closed

jobs:
  compute-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Compute new version
        id: bump_version
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          source version
          new_version=$(.github/workflows/compute_version.sh "$VERSION" "${PR_BODY//[^a-zA-Z0-9# $'\n']/}")
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

  update-version-file:
    needs: compute-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Update version file with new version
        run: |
          echo "New version: ${{ needs.compute-version.outputs.new_version }}"
          echo "VERSION=${{ needs.compute-version.outputs.new_version }}" > version
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add version
          git commit -m "chore: update version file to ${{ needs.compute-version.outputs.new_version }}"
          git push

      - name: Push new tag
        run: |
          git tag ${{ needs.compute-version.outputs.new_version }}
          git push origin ${{ needs.compute-version.outputs.new_version }}


  create-release:
    needs: [compute-version, update-version-file]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository and pull the new tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.compute-version.outputs.new_version }}

      - name: Build release packages
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            release_builder
          target: release

      - name: Copy release packages
        run: |
          mkdir -p /tmp/artifacts/
          docker run --rm -v /tmp/artifacts:/tmp/artifacts release_builder cp -r /release /tmp/artifacts/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/artifacts/release/*"
          tag: ${{ needs.compute-version.outputs.new_version }}
          body: |
            ${{ github.event.pull_request.body }}  

            This release is based on #${{ github.event.pull_request.number }} and has been published
            by release job [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

